global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['app:5001']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']