# ---

services:
  postgres:
    image: postgres:16.4-alpine
    container_name: "image-processor-postgres"
    environment:
      POSTGRES_DB: "image-processor"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "localpass"
    volumes:
      - image-processor-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5400:5432"

volumes:
  image-processor-postgres:
    driver: local
    name: image-processor-postgres
