# ---

services:
  app:
    build: .
    image: image-processor-backend:latest
    container_name: backend
    ports:
      - "5001:5001"
    healthcheck:
      test: wget -nv -t1 --spider http://localhost:5001/ping/
      interval: 5s
      timeout: 5s
      retries: 5
    restart: no
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2048M
        reservations:
          cpus: '1'
          memory: 1024M

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./benchmark/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command: --web.enable-remote-write-receiver --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - app
      - cadvisor

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ./benchmark/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./benchmark/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./benchmark/grafana/dashboards-json:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  grafana-data:
    driver: local
    name: image-processor-benchmark-grafana

  prometheus-data:
    driver: local
    name: image-processor-benchmark-prometheus
