# ---

include:
  - docker-compose.dev.yml

services:
  app:
    build: .
    image: image-processor-backend:latest
    container_name: backend
    command: sh -c "sleep 5 && npm run migrate && node ./compiled/source/api.js"
    ports:
      - "5001:5001"
    volumes:
      - ./source/metrics-output.csv:/app/compiled/source/metrics-output.csv
    healthcheck:
      test: wget -nv -t1 --spider http://localhost:5001/ping/
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
        required: true

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "9100:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./benchmark/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - app
      - cadvisor

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./benchmark/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./benchmark/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./benchmark/grafana/dashboards-json:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  k6:
    image: grafana/k6
    container_name: k6
    volumes:
      - ./benchmark/k6:/k6
    command: run /k6/k6.js # image entrypoint is 'k6'
    depends_on:
      app:
        condition: service_healthy
        required: true

volumes:
  grafana-data:
    driver: local
    name: image-processor-benchmark-grafana

  prometheus-data:
    driver: local
    name: image-processor-benchmark-prometheus
