{
 "title": "Backend",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RPS + VUs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(k6_http_reqs_total{name=\"http://app:5001/image/process-native-direct\"}[15s])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(k6_http_reqs_total{name=\"http://app:5001/image/process-wasm-direct\"}[15s])",
     "legendFormat": "{{name}}"
    },
    { "expr": "k6_vus", "legendFormat": "Virtual Users" }
   ]
  },
  {
   "title": "Cpu Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total {name=\"backend\"}[10s]) * 100",
     "legendFormat": "App Container"
    }
   ]
  },
  {
   "title": "Average Response Time (s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "k6_http_req_duration_avg{name=\"http://app:5001/image/process-native-direct\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "k6_http_req_duration_avg{name=\"http://app:5001/image/process-wasm-direct\"}",
     "legendFormat": "{{name}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM Usage (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(container_memory_rss {name=\"backend\"}) / 1024 / 1024",
     "legendFormat": "App Container"
    }
   ]
  }
 ]
}