# ---

name: 'CI/CD'

on: 
    push:
        branches: [master]

jobs:
    lint:
        runs-on: ubuntu-22.04

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup Docker
            uses: docker/setup-buildx-action@v3

          - name: Run backend
            run: | 
              docker compose create app
              docker compose start app

          - name: Run linter
            run: docker compose exec -T app npm run lint

    test:
        runs-on: ubuntu-22.04

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup Docker
            uses: docker/setup-buildx-action@v3

          - name: Run backend
            run: | 
              docker compose create app
              docker compose start app

          - name: Run tests
            run: docker compose exec -T app npm run test